# Generated by Django 3.0.1 on 2020-01-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='usename',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('year', models.IntegerField(null=True)),
                ('genres', models.ManyToManyField(db_table='movie_genre', related_name='movies', to='user.use')),
            ],
        ),
    ]
