# Generated by Django 3.0.1 on 2020-01-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('age', models.IntegerField(db_column='age', default=18)),
                ('sex', models.BooleanField(db_column='sex', default=False)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
