# Generated by Django 3.0.1 on 2020-01-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
