# Generated by Django 3.0.1 on 2020-01-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=100, verbose_name='movieId')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('genres', models.CharField(max_length=100, verbose_name='genres')),
            ],
        ),
        migrations.CreateModel(
            name='User_movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, verbose_name='userId')),
                ('movieId', models.CharField(max_length=100, verbose_name='movieId')),
                ('rating', models.CharField(max_length=100, verbose_name='rating')),
            ],
        ),
    ]
