# Generated by Django 3.0.1 on 2020-01-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_action',
            old_name='sorce',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='movie_cartoon',
            old_name='sorce',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='movie_comedy',
            old_name='sorce',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='movie_crime',
            old_name='sorce',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='movie_horrible',
            old_name='sorce',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='movie_love',
            old_name='sorce',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='movie_science',
            old_name='sorce',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='movie_story',
            old_name='sorce',
            new_name='score',
        ),
    ]
