# Generated by Django 3.0.1 on 2020-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200108_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=1000, verbose_name='电影编号')),
                ('movie_name', models.CharField(max_length=1000, verbose_name='片名')),
                ('movie_source', models.CharField(max_length=1000, verbose_name='海报路径')),
                ('up_time', models.CharField(max_length=1000, verbose_name='上映时间')),
                ('movie_adress', models.CharField(max_length=1000, verbose_name='影片归属地')),
                ('director', models.CharField(max_length=2000, verbose_name='导演')),
                ('actor', models.CharField(max_length=2000, verbose_name='演员表')),
                ('score', models.FloatField(max_length=2000, verbose_name='评分')),
                ('story', models.CharField(max_length=1000, verbose_name='剧情概要')),
            ],
        ),
    ]
